name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: npm i
    - run: npm run build:chrome
    - run: zip -r form-filler.zip dist
    - uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "form-filler.zip"